document.write( '<!DOCTYPE html>\n' );
document.write( '<html>\n' );
document.write( '  <head>\n' );
document.write( '    <meta charset=\"UTF-8\"/>\n' );
document.write( '    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>\n' );
document.write( '    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n' );
document.write( '    <title>Alyson Vilela - I Design Interactions and Experciece for Websites and Apps</title>\n' );
document.write( '    <meta name=\"description\" content=\"Rick Waalders - I Design 3D Visuals For Websites And Apps\"/>\n' );
document.write( '        <meta property=\"og:type\" content=\"website\"/><meta property=\"og:url\" content=\"https://a7yson.dev/\"/>\n' );
document.write( '        <meta property=\"og:title\" content=\"Alyson Vilela - UX UI Designer and Engeneering\"/>\n' );
document.write( '        <meta property=\"og:description\" content=\"Alyson Vilela - I Design Interactions and Experciece for Websites and Apps\"/>\n' );
document.write( '        <!-- IMPORTANTE FAZER -->\n' );
document.write( '        <meta property=\"og:image\" content=\"https://a7yson.dev/img/socialgraph.png\"/>\n' );
document.write( '        <meta property=\"twitter:card\" content=\"summary_large_image\"/>\n' );
document.write( '        <meta property=\"twitter:url\" content=\"https://a7yson.dev/\"/>\n' );
document.write( '        <meta property=\"twitter:title\" content=\"Alyson Vilela - Portifolio\"/>\n' );
document.write( '        <meta property=\"twitter:image\" content=\"https://a7yson.dev/img/socialgraph.png\"/>\n' );
document.write( '    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x\" crossorigin=\"anonymous\">\n' );
document.write( '    <link rel=\"stylesheet\" href=\"css/main.css\">\n' );
document.write( '</head>\n' );
document.write( '    <body>\n' );
document.write( '        <!-- navbar -->\n' );
document.write( '        <nav class=\"navbar navbar-expand-lg navbar-dark\">\n' );
document.write( '            <div class=\"container\">\n' );
document.write( '              <a class=\"navbar-brand\" href=\"#\"><svg class=\"me-2\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"31.328\" height=\"28.354\" viewBox=\"0 0 31.328 28.354\">\n' );
document.write( '                <defs>\n' );
document.write( '                  <linearGradient id=\"linear-gradient\" x1=\"3.051\" y1=\"-0.176\" x2=\"-10.023\" y2=\"3.448\" gradientUnits=\"objectBoundingBox\">\n' );
document.write( '                    <stop offset=\"0\" stop-color=\"#c51f4a\"/>\n' );
document.write( '                    <stop offset=\"1\" stop-color=\"#f15b27\"/>\n' );
document.write( '                  </linearGradient>\n' );
document.write( '                  <linearGradient id=\"linear-gradient-2\" x1=\"2.769\" y1=\"-0.616\" x2=\"-10.935\" y2=\"6.588\" xlink:href=\"#linear-gradient\"/>\n' );
document.write( '                </defs>\n' );
document.write( '                <g id=\"a7-logo\" transform=\"translate(-2.81 -154.99)\">\n' );
document.write( '                  <path id=\"Caminho_273\" data-name=\"Caminho 273\" d=\"M18.911,168.259a8.936,8.936,0,0,1,2.461-.612c.129-.214.255-.43.385-.643,1.413-2.317,1.529-4.155-.035-6.348a65.266,65.266,0,0,1-3.241-5.665L2.81,183.312c3.041,0,5.545-.069,8.042.028a2.608,2.608,0,0,0,2.7-1.6q.468-.867.933-1.736a8.481,8.481,0,0,1-.82-3.005A8.368,8.368,0,0,1,18.911,168.259Z\" transform=\"translate(0 0)\" fill=\"url(#linear-gradient)\"/>\n' );
document.write( '                  <path id=\"Caminho_274\" data-name=\"Caminho 274\" d=\"M1275.611,1602a6.542,6.542,0,0,0-7.3-2.8,7.8,7.8,0,0,0-1.018.332,7.019,7.019,0,0,0-4.388,7.352,7.252,7.252,0,0,0,.3,1.532,6.379,6.379,0,0,0,5.554,4.637c4.179.353,8.411.085,13.244.085C1279.739,1609.154,1277.874,1605.447,1275.611,1602Z\" transform=\"translate(-1247.864 -1430.004)\" fill=\"url(#linear-gradient-2)\"/>\n' );
document.write( '                </g>\n' );
document.write( '              </svg>Alyson Vilela</a>\n' );
document.write( '              <button class=\"navbar-toggler border-0\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n' );
document.write( '                <span class=\"navbar-toggler-icon\"></span>\n' );
document.write( '              </button>\n' );
document.write( '              <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n' );
document.write( '                <ul class=\"navbar-nav ms-auto\">\n' );
document.write( '                  <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"pe-0 nav-link active\" aria-current=\"work\" href=\"#\">Work</a>\n' );
document.write( '                  </li>\n' );
document.write( '                  <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"pe-0 nav-link\" href=\"#\">Portifolio</a>\n' );
document.write( '                  </li>\n' );
document.write( '                  <li class=\"nav-item\">\n' );
document.write( '                    <a class=\"pe-0 nav-link\" href=\"#\">About</a>\n' );
document.write( '                  </li>\n' );
document.write( '                </ul>\n' );
document.write( '              </div>\n' );
document.write( '            </div>\n' );
document.write( '          </nav>\n' );
document.write( '\n' );
document.write( '          <!-- <div class=\"col a7-dev\"><img src=\"assets/icons/a7dev.svg\" alt=\"Development icon\"></div>\n' );
document.write( '          <div class=\"col a7edu\"><img src=\"assets/icons/a7edu.svg\" alt=\"Education icon\"></div> -->\n' );
document.write( '\n' );
document.write( '          \n' );
document.write( '          <section id=\"home\">\n' );
document.write( '              <div class=\"container py-3 py-md-5\">\n' );
document.write( '                    <div class=\"text-par col-12 text-center w-75 w-lg-50 mx-auto py-4\">\n' );
document.write( '                        <h1>Hi, I\'m Alyson</h1>\n' );
document.write( '                        <p class=\"p-display\">I develop civil engeneering projects and interfaces for apps and websites.</p>\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"pics col-8 col-md-4 mx-auto\">\n' );
document.write( '                        <div><img class=\"floating\" src=\"assets/icons/head-illustration.svg\" alt=\"Alyson\'s Illustration\"></div>\n' );
document.write( '                    </div>\n' );
document.write( '                    <a href=\"#about\"><div class=\"scroll-down floating-4\"></div></a>\n' );
document.write( '              </div>\n' );
document.write( '          </section>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '          <!-- <div class=\"col a7-dev\"><img src=\"assets/icons/a7dev.svg\" alt=\"Development icon\"></div>\n' );
document.write( '          <div class=\"col a7-edu\"><img src=\"assets/icons/a7edu.svg\" alt=\"Education icon\"></div> -->\n' );
document.write( '\n' );
document.write( '        <!-- Section about -->\n' );
document.write( '        <section id=\"about\">\n' );
document.write( '            <div class=\"container py-3 py-md-5\">\n' );
document.write( '                <div class=\"row\">\n' );
document.write( '                    <div class=\"text-part text-center text-md-start col-12 col-lg-4\">\n' );
document.write( '                        <h2>Who I am</h2>\n' );
document.write( '                        <p>I\'ve been a UX and UI designer for over 5 years, aweb development enthusiast and passionate about problem solving (physics or not).</p>\n' );
document.write( '                        <p>I\'m also learning and sharing educational subjects on my <a class=\"p p-purple href\" href=\"https://twitch.tv/a7yson\">Twitch</a> channel.</p>\n' );
document.write( '                        <a href=\"about.html\" class=\"btn-red btn-blue-transparent w-100 my-3\">More about me</a>\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"pics d-flex justify-content-center align-center col-12 col-lg-8\">\n' );
document.write( '                        <div class=\"text-part col\">\n' );
document.write( '                            <div class=\"a7-dev d-flex justify-content-center py-3\">\n' );
document.write( '                                <h4 class=\"p p-white align-self-center pe-1\" style=\"font-size: 1rem;\">A7</h4><h3 class=\"p-red\">DEV</h3>\n' );
document.write( '                            </div>\n' );
document.write( '                            <div class=\"pb-3 \"><img class=\"img-fluid mx-auto pe-1 p-md-2 floating-2\" src=\"assets/icons/a7-dev.svg\" alt=\"Development icon\"></div>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"text-part col\">\n' );
document.write( '                            <div class=\"a7-dev d-flex justify-content-center py-3\">\n' );
document.write( '                                <h4 class=\"p p-white align-self-center pe-1\" style=\"font-size: 1rem;\">A7</h4><h3 class=\"p-blue\">EDU</h3>\n' );
document.write( '                            </div>\n' );
document.write( '                            <div class=\"pb-3\"><img class=\"img-fluid mx-auto ps-1 p-md-2 floating-3\" src=\"assets/icons/a7-edu.svg\" alt=\"Education icon\"></div>\n' );
document.write( '                        </div>\n' );
document.write( '                        </div>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '        </section>\n' );
document.write( '\n' );
document.write( '            <section id=\"sep\" class=\"text-center py-3 background-red\">\n' );
document.write( '                <h3>PROJECTS</h3>\n' );
document.write( '            </section>\n' );
document.write( '\n' );
document.write( '        <!-- Section Portifolio -->\n' );
document.write( '        <section id=\"portfolio\">\n' );
document.write( '            <div class=\"business-1\">\n' );
document.write( '                <div class=\"container py-3 py-md-5\">\n' );
document.write( '                    <div class=\"row\">\n' );
document.write( '                        <div class=\"business-1 pb-3 pb-md-5\">\n' );
document.write( '                            <div class=\"text-part text-center w-75 mx-auto\">\n' );
document.write( '                                <h2>ESM Revestimentos</h2>\n' );
document.write( '                                <p>UX, UI, Brand guidelines, Website development.</p>\n' );
document.write( '                            </div>\n' );
document.write( '                            <div class=\"pics\">\n' );
document.write( '                                <div class=\"large-pic\"><img src=\"assets/esm/large-esm.jpg\" class=\"img-fluid col-12\" alt=\"ESM Principal Project\"></div>\n' );
document.write( '                                <div class=\"medium-pic d-flex py-3\">\n' );
document.write( '                                    <div class=\"medium-pic col pe-3\"><img src=\"assets/esm/medium2-esm.jpg\" class=\"img-fluid\" style=\"width: 100%;\" alt=\"ESM Guideline Cover\"></div>\n' );
document.write( '                                    <div class=\"medium-pic col\"><img src=\"assets/esm/medium-esm.jpg\" class=\"img-fluid\" style=\"width: 100%;\" alt=\"Work documents\"></div>\n' );
document.write( '                                </div>\n' );
document.write( '                            </div>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"business-2 py-3 py-md-5\">\n' );
document.write( '                            <div class=\"text-part text-center w-75 mx-auto\">\n' );
document.write( '                                <h2>DIT.</h2>\n' );
document.write( '                                <p>Logo, UX and UI Design.</p>\n' );
document.write( '                            </div>\n' );
document.write( '                            <div class=\"pics\">\n' );
document.write( '                                <div class=\"large-pic\"><img src=\"assets/esm/large-esm.jpg\" class=\"img-fluid col-12\" alt=\"ESM Principal Project\"></div>\n' );
document.write( '                                <div class=\"medium-pic d-flex py-3\">\n' );
document.write( '                                    <div class=\"medium-pic col pe-3\"><img src=\"assets/esm/medium2-esm.jpg\" class=\"img-fluid\" style=\"width: 100%;\" alt=\"ESM Guideline Cover\"></div>\n' );
document.write( '                                    <div class=\"medium-pic col\"><img src=\"assets/esm/medium-esm.jpg\" class=\"img-fluid\" style=\"width: 100%;\" alt=\"Work documents\"></div>\n' );
document.write( '                                </div>\n' );
document.write( '                            </div>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"business-3 py-3 py-md-5\">\n' );
document.write( '                            <div class=\"text-part text-center w-75 mx-auto\">\n' );
document.write( '                                <h2>MDNZ Projetos e Construções</h2>\n' );
document.write( '                                <p>Brand design, civil engeneering post selling book, educational artwork for social media.</p>\n' );
document.write( '                            </div>\n' );
document.write( '                            <div class=\"pics\">\n' );
document.write( '                                <div class=\"large-pic\"><img src=\"assets/esm/large-esm.jpg\" class=\"img-fluid col-12\" alt=\"ESM Principal Project\"></div>\n' );
document.write( '                                <div class=\"medium-pic d-flex py-3\">\n' );
document.write( '                                    <div class=\"medium-pic col pe-3\"><img src=\"assets/esm/medium2-esm.jpg\" class=\"img-fluid\" style=\"width: 100%;\" alt=\"ESM Guideline Cover\"></div>\n' );
document.write( '                                    <div class=\"medium-pic col\"><img src=\"assets/esm/medium-esm.jpg\" class=\"img-fluid\" style=\"width: 100%;\" alt=\"Work documents\"></div>\n' );
document.write( '                                </div>\n' );
document.write( '                            </div>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"business-4 py-3 py-md-5\">\n' );
document.write( '                            <div class=\"text-part text-center w-75 mx-auto\">\n' );
document.write( '                                <h2>LUTEC</h2>\n' );
document.write( '                                <p>Brand design.</p>\n' );
document.write( '                            </div>\n' );
document.write( '                            <div class=\"pics\">\n' );
document.write( '                                <div class=\"large-pic\"><img src=\"assets/esm/large-esm.jpg\" class=\"img-fluid col-12\" alt=\"ESM Principal Project\"></div>\n' );
document.write( '                                <div class=\"medium-pic d-flex py-3\">\n' );
document.write( '                                    <div class=\"medium-pic col pe-3\"><img src=\"assets/esm/medium2-esm.jpg\" class=\"img-fluid\" style=\"width: 100%;\" alt=\"ESM Guideline Cover\"></div>\n' );
document.write( '                                    <div class=\"medium-pic col\"><img src=\"assets/esm/medium-esm.jpg\" class=\"img-fluid\" style=\"width: 100%;\" alt=\"Work documents\"></div>\n' );
document.write( '                                </div>\n' );
document.write( '                            </div>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"business-5 py-3 py-md-5\">\n' );
document.write( '                            <div class=\"text-part text-center w-75 mx-auto\">\n' );
document.write( '                                <h2>CASEC</h2>\n' );
document.write( '                                <p>Development of civil engeneering projects and services to needy communities in Caraguatatuba - SP.</p>\n' );
document.write( '                            </div>\n' );
document.write( '                            <div class=\"pics\">\n' );
document.write( '                                <div class=\"large-pic\"><img src=\"assets/esm/large-esm.jpg\" class=\"img-fluid col-12\" alt=\"ESM Principal Project\"></div>\n' );
document.write( '                                <div class=\"medium-pic d-flex py-3\">\n' );
document.write( '                                    <div class=\"medium-pic col pe-3\"><img src=\"assets/esm/medium2-esm.jpg\" class=\"img-fluid\" style=\"width: 100%;\" alt=\"ESM Guideline Cover\"></div>\n' );
document.write( '                                    <div class=\"medium-pic col\"><img src=\"assets/esm/medium-esm.jpg\" class=\"img-fluid\" style=\"width: 100%;\" alt=\"Work documents\"></div>\n' );
document.write( '                                </div>\n' );
document.write( '                            </div>\n' );
document.write( '                        </div>\n' );
document.write( '\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '        </section>\n' );
document.write( '        \n' );
document.write( '\n' );
document.write( '\n' );
document.write( '          <!-- footer -->\n' );
document.write( '          <footer class=\"container\">\n' );
document.write( '              <hr class=\"divider my-3\">\n' );
document.write( '              <div class=\"boxes my-5\">\n' );
document.write( '                  <div class=\"row\">\n' );
document.write( '                    <div class=\"box-left col-lg-5\">\n' );
document.write( '                      <div class=\"box1\">\n' );
document.write( '                        <div class=\"title d-flex\">\n' );
document.write( '                            <svg class=\"me-2\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"31.328\" height=\"28.354\" viewBox=\"0 0 31.328 28.354\">\n' );
document.write( '                                <defs>\n' );
document.write( '                                  <linearGradient id=\"linear-gradient\" x1=\"3.051\" y1=\"-0.176\" x2=\"-10.023\" y2=\"3.448\" gradientUnits=\"objectBoundingBox\">\n' );
document.write( '                                    <stop offset=\"0\" stop-color=\"#c51f4a\"/>\n' );
document.write( '                                    <stop offset=\"1\" stop-color=\"#f15b27\"/>\n' );
document.write( '                                  </linearGradient>\n' );
document.write( '                                  <linearGradient id=\"linear-gradient-2\" x1=\"2.769\" y1=\"-0.616\" x2=\"-10.935\" y2=\"6.588\" xlink:href=\"#linear-gradient\"/>\n' );
document.write( '                                </defs>\n' );
document.write( '                                <g id=\"a7-logo\" transform=\"translate(-2.81 -154.99)\">\n' );
document.write( '                                  <path id=\"Caminho_273\" data-name=\"Caminho 273\" d=\"M18.911,168.259a8.936,8.936,0,0,1,2.461-.612c.129-.214.255-.43.385-.643,1.413-2.317,1.529-4.155-.035-6.348a65.266,65.266,0,0,1-3.241-5.665L2.81,183.312c3.041,0,5.545-.069,8.042.028a2.608,2.608,0,0,0,2.7-1.6q.468-.867.933-1.736a8.481,8.481,0,0,1-.82-3.005A8.368,8.368,0,0,1,18.911,168.259Z\" transform=\"translate(0 0)\" fill=\"url(#linear-gradient)\"/>\n' );
document.write( '                                  <path id=\"Caminho_274\" data-name=\"Caminho 274\" d=\"M1275.611,1602a6.542,6.542,0,0,0-7.3-2.8,7.8,7.8,0,0,0-1.018.332,7.019,7.019,0,0,0-4.388,7.352,7.252,7.252,0,0,0,.3,1.532,6.379,6.379,0,0,0,5.554,4.637c4.179.353,8.411.085,13.244.085C1279.739,1609.154,1277.874,1605.447,1275.611,1602Z\" transform=\"translate(-1247.864 -1430.004)\" fill=\"url(#linear-gradient-2)\"/>\n' );
document.write( '                                </g>\n' );
document.write( '                              </svg>\n' );
document.write( '                              <h3>Get in touch!</h3>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"text-and-image row\">\n' );
document.write( '                            <p class=\"p-display-low p-white col-7\">If you want to work together on a project or just have a chat, please don\'t hesitate to contact me via email below.</p>\n' );
document.write( '                            <img class=\"img-fluid col-5 h-100\" src=\"assets/header.png\" alt=\"Icon Alyson\">\n' );
document.write( '                          </div>\n' );
document.write( '                              <button class=\"btn-red w-100 my-3\" type=\"button\">Send me an email</button>\n' );
document.write( '                      </div>\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"box-right col-lg-7\">\n' );
document.write( '                      <div class=\"box text-center text-lg-end my-5 my-lg-0\">\n' );
document.write( '                          <div class=\"links\">\n' );
document.write( '                              <a href=\"#\" aria-current=\"work\"><h3 class=\"pb-1 active\">WORK</h3></a>\n' );
document.write( '                              <a href=\"#\"><h3 class=\"pb-1 link-hold\">PORTIFOLIO</h3 class=\"link-hold\"></a>\n' );
document.write( '                              <a href=\"#\"><h3 class=\"pb-1 link-hold\">ABOUT</h3></a>\n' );
document.write( '                          </div>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"box\">\n' );
document.write( '                          <ul class=\"d-flex flex-row justify-content-center justify-content-lg-end px-0\">\n' );
document.write( '                            <li><a href=\"https://github.com/alysonvilela/\" class=\"px-2 p-white\"><i alt=\"github\" class=\"fab fa-github\"></i></a></li>\n' );
document.write( '                            <li><a href=\"https://instagram.com/a7yson\" class=\"px-2 p-white\"><i alt=\"instagram\" class=\"fab fa-instagram\"></i></a></li>\n' );
document.write( '                            <li><a href=\"https://twitch.tv/a7yson\" class=\"px-2 p-white\"><i alt=\"twitch\" class=\"fab fa-twitch\"></i></a></li>\n' );
document.write( '                          </ul>\n' );
document.write( '                        </div>\n' );
document.write( '                    </div> \n' );
document.write( '                      </div>\n' );
document.write( '                  </div>\n' );
document.write( '              </div>\n' );
document.write( '              </div>\n' );
document.write( '          </footer>\n' );
document.write( '        <!-- Scripts -->\n' );
document.write( '    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\" integrity=\"sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p\" crossorigin=\"anonymous\"></script>\n' );
document.write( '    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js\" integrity=\"sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT\" crossorigin=\"anonymous\"></script>\n' );
document.write( '    <script src=\"https://kit.fontawesome.com/2f1642c9ea.js\" crossorigin=\"anonymous\"></script>\n' );
document.write( '    </body>\n' );
document.write( '</html>' );
